In [1]:
import pandas as pd

In [3]:
columns = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv('C:\VIVEK\GIT\pandas\data\TEST_DATA_pima-indians-diabetes.data', names=columns)

In [20]:
#print(data)
print(data.describe())

             preg        plas        pres        skin        test        mass  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

             pedi         age       class  
count  768.000000  768.000000  768.000000  
mean     0.471876   33.240885    0.348958  
std      0.331329   11.760232    0.476951  
min      0.078000   21.000000    0.000000  
25%      0.243750   24.000000    0.000000  
50%   

In [23]:
print(data.hist())

[[<matplotlib.axes._subplots.AxesSubplot object at 0x0000027625A43518>


In [24]:
data.groupby('class').hist()

class
0    [[AxesSubplot(0.125,0.670278;0.215278x0.209722...
1    [[AxesSubplot(0.125,0.670278;0.215278x0.209722...
dtype: object

In [19]:
import matplotlib.pyplot as plt
pd.options.display.mpl_style = 'default' 
data.boxplot()

OptionError: 'You can only set the value of existing options'

In [28]:
from pandas.plotting import scatter_matrix
scatter_matrix(data)

array([[<matplotlib.axes._subplots.AxesSubplot object at 0x00000276286E3278>,
        <matplotlib.axes._subplots.AxesSubplot object at 0x000002762A78AC18>]], dtype=object)

In [51]:
#series_data = pd.Series(data=data["preg"])

dictTemp = {'col1':'val1','col2':'val2'}
lstVals = ['val1','val2','val3']
series_lstVals = pd.Series(data=lstVals)
print(series_lstVals)
series_dictTemp = pd.Series(data=dictTemp)
print(series_dictTemp)
print(series_dictTemp.index)
print(series_dictTemp.values)

0    val1
1    val2
2    val3
dtype: object
col1    val1
col2    val2
dtype: object
Index(['col1', 'col2'], dtype='object')
['val1' 'val2']


In [65]:
import numpy 
s = pd.Series([1,'z',5,numpy.nan,19,'a'])
s

0      1
1      z
2      5
3    NaN
4     19
5      a
dtype: object

In [85]:
dt = pd.date_range('20180101',periods=6)
print(dt)
df1 = pd.DataFrame(numpy.random.rand(6,3),index=dt,columns=list('xyz'))
print(df1)
print(df1.dtypes)
#print(dataFrame.<TAB>)


DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')
                   x         y         z
2018-01-01  0.788234  0.270889  0.751455
2018-01-02  0.784005  0.407926  0.227960
2018-01-03  0.450843  0.405407  0.061757
2018-01-04  0.143222  0.880716  0.060288
2018-01-05  0.516208  0.469951  0.646536
2018-01-06  0.544677  0.535225  0.421877
x    float64
y    float64
z    float64
dtype: object


In [83]:
#dataFrame = pd.DataFrame({'col1' : 10,'col2' : 'test'})
#dataFrame

In [91]:
print(df1.index)
print(df1.columns)
print(df1.values)
print(df1.head)
#T - transpose / pivote
print(df1.T)


DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['x', 'y', 'z'], dtype='object')
[[ 0.78823441  0.27088942  0.75145452]
 [ 0.78400526  0.40792612  0.22796039]
 [ 0.45084313  0.40540727  0.06175661]
 [ 0.14322225  0.88071627  0.06028835]
 [ 0.51620766  0.46995086  0.64653607]
 [ 0.54467688  0.53522532  0.42187651]]
<bound method NDFrame.head of                    x         y         z
2018-01-01  0.788234  0.270889  0.751455
2018-01-02  0.784005  0.407926  0.227960
2018-01-03  0.450843  0.405407  0.061757
2018-01-04  0.143222  0.880716  0.060288
2018-01-05  0.516208  0.469951  0.646536
2018-01-06  0.544677  0.535225  0.421877>
   2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05  2018-01-06
x    0.788234    0.784005    0.450843    0.143222    0.516208    0.544677
y    0.270889    0.407926    0.405407    0.880716    0.469951    0.535225
z    0.751455    0.2279

In [102]:
#sorting axis
print(df1.sort_index(axis=1))
print(df1.sort_index(axis=1,ascending=False))

                   x         y         z
2018-01-01  0.788234  0.270889  0.751455
2018-01-02  0.784005  0.407926  0.227960
2018-01-03  0.450843  0.405407  0.061757
2018-01-04  0.143222  0.880716  0.060288
2018-01-05  0.516208  0.469951  0.646536
2018-01-06  0.544677  0.535225  0.421877
                   z         y         x
2018-01-01  0.751455  0.270889  0.788234
2018-01-02  0.227960  0.407926  0.784005
2018-01-03  0.061757  0.405407  0.450843
2018-01-04  0.060288  0.880716  0.143222
2018-01-05  0.646536  0.469951  0.516208
2018-01-06  0.421877  0.535225  0.544677


In [108]:
#sorting values
print(df1.sort_values(by='x',ascending=False))
print(df1.sort_values(by='z'))

                   x         y         z
2018-01-01  0.788234  0.270889  0.751455
2018-01-02  0.784005  0.407926  0.227960
2018-01-06  0.544677  0.535225  0.421877
2018-01-05  0.516208  0.469951  0.646536
2018-01-03  0.450843  0.405407  0.061757
2018-01-04  0.143222  0.880716  0.060288
                   x         y         z
2018-01-04  0.143222  0.880716  0.060288
2018-01-03  0.450843  0.405407  0.061757
2018-01-02  0.784005  0.407926  0.227960
2018-01-06  0.544677  0.535225  0.421877
2018-01-05  0.516208  0.469951  0.646536
2018-01-01  0.788234  0.270889  0.751455
